spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/UserServiceDb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
github:
    username: ${GITHUB_USERNAME}
    token: ${GITHUB_TOKEN}
