spring:
  datasource:
    url: jdbc:postgresql://postgresql_user-service:5432/UserServiceDB
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
app:
  env:
    local: true
jwt:
  secret: ${JWT_SECRET}
guest:
  password: ${GUEST_PASSWORD}
eureka:
  client:
    enabled: false