spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservicedb
    username: username
    password: password
  kafka:
    bootstrap-servers: aron:9092
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
app:
  env:
    # Fixme
    local: true

eureka:
  client:
    enabled: false