spring:
  application:
    name: userservice
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: jdbc:postgresql://localhost:5432/UserServiceDb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
github:
    username: ${GITHUB_USERNAME}
    token: ${GITHUB_TOKEN}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/