spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservicedb
    username: username
    password: password
  kafka:
    bootstrap-servers: 127.0.1.1:9092
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    enabled: false

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

