spring:
datasource:
  url: jdbc:postgresql://localhost:5432/UserServiceDB
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    '[hypersistence.utils.enable_types_contributor]': false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  env:
    local: true

jwt:
  secret: ${JWT_SECRET}

guest:
  password: ${GUEST_PASSWORD}
